use crate::bot::{Move, Player};

/// Plays moves according to fixed de Bruijn sequences.
///
/// 13 sequences of order 4 on size-3 alphabet
/// (length = 3 ** 4 = 81)
///
/// 13 * 81 = 1053
/// (53 entries seem to be missing?)
pub struct DeBruijnDummy {
    index: usize,
}

const SEQUENCE: &str = "PRSRRSRSRPPRRSSPRRPPSSRRPSPRSSSSRPSRSSRSPPSPPRPPPSRRRRSPRPRPSSPSRPRRRPRSPSPSSSPPPRRPPPPRPRSSSRRSSRSRPRPPRSPPSSSSPPPSRPSSPSRRRPRRRRSRSSPRRPSPSSRPPSPPRRSPRPSRSPSPRSPPSRRPRPSSRPRRSRPSRPPSPPPPRSRSPRSSRSSSSRRRPSPSSSPPRPPRRRRSPSRSRRSSPRRPPPSSPSPRPRSPRPRSRSRRPSSSRSPRRPPPSSPPRSSRRRSSSSPSSRPSRRSRPPSPSPPPPRRSPSRPRRRRPRPPRPSPRSPPSRSSSSPPPPRRSRSSSPSPRSPRRRRSPPSSPRPRRPPPSPPRPSSSSRRPSRSRPSPSRPRPPSRRRPRSSRSPSSRPPRSRRRRRRPRRRSPPRRPPPPRSRSPSRSSPSSSPPPSPSPRRSRPPRPRSPRSSSSRSRRSSRRPSSPRPPSRPSPPSSRPRPSSSRSRRSRSPSSSSRRRRSSPRRRPSRPSPSRRPRSRPRRSPRPSSPPSRSSSPSPRSSRPPRSPPRRPPSPPPPRPRPPPPPPSPRRRRPPRSPSPSSSRRPSRPRPSPPSSRSRSPPRRPRSRRSRPPSRSSPPPPRPRRSSSSPSRRRSPRSSRPSSPRSPRPRPPPPSPPRPSPSSSSPSRRRPPSRSRSPRRRRSRRPRRSSSRRSPPSSRPSRPPRRPSSPPPRSRPRSSRSSPRSPSSSPRPRSSPSRSPRSRRRRPSPRRSRSSRPRPPSPPRRPRRRSPPSRRSSSSRRPPPRSPSPSSPPPPSSRSRPSRPPRPPRRPPRPSRPSPSSPRRSRSPRPRSSRPPSPRSRRPRPPPSSSSPSRSSPPSRRSPSPPPPRSPPRRRRSSSRRRPSSRSRSSRSPPSRSRRPPPRRPSPPRPPRSSRRSSPPPPSPSPRSRSSSSPSRRRPRRSPRRRRSRPPSSSRPSSPRPRPSRPRSPRSRSPPPRRSSSRPPSSPSRRRPRPSPR";

impl Player for DeBruijnDummy {
    fn new() -> Self {
        Self { index: 0 }
    }

    fn make_move(&mut self, _opp_prev_moves: &[Move]) -> Move {
        let result = match SEQUENCE.as_bytes()[self.index] {
            b'R' => Move::Rock,
            b'P' => Move::Paper,
            _ => Move::Scissors,
        };

        self.index += 1;
        if self.index == SEQUENCE.len() {
            self.index = 0
        }

        result
    }
}
